version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/fsouza/go-dockerclient
    versions:
    - 1.7.0
    - 1.7.1
